### ISSUE TITLE
Count placing a correct shape out of order as a success

### ISSUE THREAD

**Issue by xen-osd** [open-manifold/Open-Manifold#10]
In the original Rhythm 'N' Face, the player can place shapes in the correct places out of turn, for example placing a character's nose in the right spot even though the CPU moves are making an eye.

**Comment by SuperFromND** [comment]
I... actually didn't know that was a thing in RnF!

It's not *too* hard to add this in theory, but I think from a gameplay standpoint that will lead to confusion (like if a player accidentally screws up and just *happens* to get a correct shape placement by sheer coincidence). I think it'll be best to leave the current behavior as-is, inaccurate to the source as it may be.
