### ISSUE TITLE
Back button for changing the color in sandbox mode

### ISSUE THREAD

**Issue by xen-osd** [open-manifold/Open-Manifold#11]
Currently, the player has only a single button to cycle through the color palette in sandbox mode. To get the color black, one has to press V 15 times, then another 11 times to cycle back to light blue. A back button, or perhaps a clickable color menu in the future, would make face creation much easier.

**Comment by SuperFromND** [comment]
I've implemented a toolbar into Sandbox that, among other things planned in the future, solves this issue! Pressing Up and Down while the "Change Color" option is selected will now let you cycle the color in that direction:

https://user-images.githubusercontent.com/22881403/212999404-9bb34985-e95d-4b83-ae0a-9deb5693b627.mp4

**Comment by xen-osd** [comment]
very awesome
