### ISSUE TITLE
Combo indicator

### ISSUE THREAD

**Issue by xen-osd** [open-manifold/Open-Manifold#14]
In the original Rhythm 'n' Face, hitting a combo of 5 or 10 causes a pop-up of clapping hands as well as a sound effect. Once the bigger problems are done with, adding a combo.png spritesheet (and combo.ogg sound) for level makers would be a minor but nice addition.

**Comment by SuperFromND** [comment]
A combo indicator and sound effect have been added; they'll display when hitting any combo that's a multiple of 5.  Here's a demo using a very easy level:

https://user-images.githubusercontent.com/22881403/213053202-3c600b89-a8c2-4967-9c00-1e0fac91fc3c.mp4

Like any other sound, this can be customized on a per-level basis (the sound's called `combo.ogg`).
