### ISSUE TITLE
The D in the open manifold logo has two-pixel gaps from where the rectangle doesn't entirely cover the circle

### ISSUE THREAD

**Issue by xen-osd** [open-manifold/Open-Manifold#16]
![image](https://user-images.githubusercontent.com/122745212/212564465-67fda611-22f5-42d8-aa48-d2cb7337d327.png)

**Comment by SuperFromND** [comment]
This has now been fixed!
![image](https://user-images.githubusercontent.com/22881403/212571247-1f38b117-fa58-41d6-bb62-41b1559bbe86.png)
No more gap. :D
