### ISSUE TITLE
Option to export Sandbox creations to png/json

### ISSUE THREAD

**Issue by xen-osd** [open-manifold/Open-Manifold#17]

**Comment by SuperFromND** [comment]
Exporting to JSON is planned as an option for the new toolbar. :)
To quote my commit message in [bf37082](https://github.com/open-manifold/Open-Manifold/commit/bf37082a00cb15b54ac3c0c3650314c848942c0e):
> I've reserved six icons in the new sandbox icons texture, so expect
to see more commits in the near future that implement more things
(some ideas I have include exporting to JSON, shape morph, color morph,
changing the color of the background, and grid toggle.)

**Comment by SuperFromND** [comment]
JSON exporting has been implemented. :+1:
