### ISSUE TITLE
Use nearest-neighbor for upscaling small character.png images

### ISSUE THREAD

**Issue by xen-osd** [open-manifold/Open-Manifold#19]
![image](https://user-images.githubusercontent.com/122745212/212766626-643b781c-7668-4b14-b27e-19c1bca2f66d.png)
It is particularly noticeable in the panda's eyes

**Comment by SuperFromND** [comment]
I tried this out as an experiment by using a method where, if the sprite was smaller than the "bounding box" that characters are drawn to, it uses nearest-neighbor, else it uses bilinear:

```cpp
    // determine whether to use NN or bilinear scaling based on
    // whether the character sprite fits into the bounding box or not
    int greater_axis = fmax(char_crop.w, char_crop.h);
    
    if (greater_axis < char_coords.w) {
        SDL_SetTextureScaleMode(char_texture, SDL_ScaleModeNearest);
    } else {
        SDL_SetTextureScaleMode(char_texture, SDL_ScaleModeLinear);
    }
```

I wasn't really fond of the resulting look though (the game doesn't use integer scaling for this, so you get inconsistent pixel sizes and it just looks weird regardless):

![image](https://user-images.githubusercontent.com/22881403/212773118-8f42806d-5cce-42f6-ab59-056824cfee26.png)
![image](https://user-images.githubusercontent.com/22881403/212773125-76f662c1-a44e-45c3-b83a-1ccf5feab7a7.png)

Perhaps this is something that could be added as an option instead, so the user can decide based on whatever looks better to them.

**Comment by SalsaGal** [comment]
Another option is that rather than an option per game, it could be an option per level?

**Comment by SuperFromND** [comment]
Yeah, this would probably make more sense as something per-level. I'm of perhaps adding a header to `character.json` to allow for this to be set there:

```json
{"scale_mode": "nearest"}
{"scale_mode": "bilinear"}
```

Since `level.json` and now `tile.json` have one, it'd only make sense character.json has one too.

**Comment by SuperFromND** [comment]
The above header and `scale_mode` parameter have now been implemented!
The parameters are named `linear` and `nearest`. Defaults to `linear`.

Still isn't scaled with integer scaling in `nearest` at the moment, but it should be good enough for now hopefully! <3
![image](https://user-images.githubusercontent.com/22881403/232168047-1a4c8630-00da-4b4f-9f9a-c0ba3b5afc9f.png)
