### ISSUE TITLE
Y/N confirmation box for exiting sandbox mode

### ISSUE THREAD

**Issue by xen-0sd** [open-manifold/Open-Manifold#31]
Right now, pressing backspace in sandbox mode immediately takes the player to the main menu. This could be destructive to players who accidentally press it when they haven't finished their shape. Not that this has happened to me, thankfully.

**Comment by SuperFromND** [comment]
![2023-06-29_04-37-56](https://github.com/open-manifold/Open-Manifold/assets/22881403/add32985-9ea6-4851-a801-daa67ed8962c)
A confirmation dialog has been added!
