### ISSUE TITLE
The center square of the Photosensitivity Warning eyeball is one pixel too high

### ISSUE THREAD

**Issue by xen-0sd** [open-manifold/Open-Manifold#36]
![sens](https://github.com/open-manifold/Open-Manifold/assets/136213157/77a872d4-fc94-42f7-82ea-f04687ea98ab)
Absolutely immersion-breaking

**Comment by SuperFromND** [comment]
This is something I've actually known about for some time! The misalignment seems to only happen at certain resolutions and is *probably* an issue with how circles are drawn. I don't even know if this is something that can be easily fixed, unfortunately. :<
